# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('responce_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('New', 'New'), ('Reject', 'Reject'), ('Accept', 'Accept')], default='Draft', max_length=20)),
                ('buyer_fb', models.BooleanField(default=False)),
                ('seller_fb', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_goods', to='callboard.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Order')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('buyer', 'seller')]),
        ),
    ]
