# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0055_attribute_key_words'),
        ('marketplace', '0003_auto_20161205_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(default=0, verbose_name='order_id')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='callboard.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(to='marketplace.OrderItems'),
        ),
    ]
