# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20161205_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во'),
            preserve_default=False,
        ),
    ]
