# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_orderitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
