# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_deliverttype_deliveryoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='field_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Choice', 'Choice'), ('Int', 'Int')], default='Text', max_length=20, verbose_name=''),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
