# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20161205_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelivertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Транспортная компания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=60, verbose_name='Опция доставки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('field_type', models.CharField(choices=[('Text', 'Text'), ('Choice', 'Choice'), ('Int', 'Int')], default='Text', max_length=20, verbose_name='')),
                ('delivery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.DelivertType')),
            ],
        ),
    ]
