# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(blank=True, max_length=70)),
                ('follow', models.ManyToManyField(blank=True, related_name='articles_follow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Имя форума')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('image', models.ImageField(blank=True, upload_to=community.models.get_upload_file_name, verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=70)),
                ('follow', models.ManyToManyField(blank=True, related_name='forums_follow', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Forums', verbose_name='Форум'),
        ),
        migrations.AddField(
            model_name='articles',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
