# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20160408_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='official_status',
            field=models.BooleanField(default=True),
        ),
    ]
