# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_forums_official_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='forums',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
    ]
