# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20160504_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
    ]
