# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-03 13:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callboard', '0029_auto_20160923_1325'),
        ('auction', '0002_auto_20161003_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('start_price', models.IntegerField(verbose_name='Начальная цена')),
                ('end_price', models.IntegerField(verbose_name='Экспресс цена')),
                ('min_price_step', models.IntegerField(verbose_name='Минимальный шаг цены')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата завершения')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date_update')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard.Goods')),
            ],
        ),
    ]
