# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Аукцион завершен'),
        ),
    ]
