# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_canceled',
        ),
    ]
