# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0032_goods_is_aukc'),
        ('auction', '0006_remove_auction_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product',
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.ManyToManyField(to='callboard.Goods'),
        ),
    ]
