# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0032_goods_is_aukc'),
        ('auction', '0007_auto_20161004_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product',
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='callboard.Goods'),
            preserve_default=False,
        ),
    ]
