# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_bets_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Экспресс цена'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_price_step',
            field=models.PositiveIntegerField(verbose_name='Минимальный шаг цены'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.PositiveIntegerField(verbose_name='Начальная цена'),
        ),
    ]
