# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:24
from __future__ import unicode_literals

import advdesk.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Объявление')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=advdesk.models.get_upload_file_name)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advdesk.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Подкатегория')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advdesk.Category', verbose_name='Карегория')),
                ('user', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advdesk.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('category_id', 'name')]),
        ),
    ]
