# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 10, 10, 27, 4, 684306, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
