# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advdesk', '0006_auto_20160210_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('category', 'name')]),
        ),
    ]
