# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('advdesk', '0008_goods_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(max_length=30, verbose_name='Аттрибут')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advdesk.Category', verbose_name='Карегория')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='advdesk.SubCategory', verbose_name='Подкатегория')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='test',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
