# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advdesk', '0009_auto_20160210_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя аттрибута')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategoryattr',
            name='attrname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='advdesk.Attributes', verbose_name='Аттрибут'),
        ),
    ]
