# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advdesk', '0010_auto_20160210_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryattr',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoryattr',
            unique_together=set([('category', 'subcategory', 'attrname')]),
        ),
    ]
