# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, upload_to='', verbose_name='Аватар')),
                ('adress_city', models.CharField(blank=True, max_length=60, verbose_name='Город')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by_user', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
