# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='/static/images/avatar.jpeg', upload_to='', verbose_name='Аватар'),
        ),
    ]
