# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20161012_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileTable',
        ),
    ]
