# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20161012_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiletable',
            name='user_image',
            field=models.ImageField(blank=True, default='/static/avatar.jpeg', upload_to='', verbose_name='Аватар'),
        ),
    ]
