# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20161121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiletable',
            name='user_image',
            field=models.ImageField(blank=True, default='avatar.jpeg', upload_to=userprofile.models.get_upload_file_name, verbose_name='Аватар'),
        ),
    ]
