# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20161130_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletable',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение'),
        ),
    ]
