# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofiletable_last_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Credit', 'Снятие'), ('Debit', 'Пополнение')], max_length=10)),
                ('operation_ammount', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Время операци')),
            ],
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='phone1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='shop_adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='shop_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание магазина'),
        ),
        migrations.AddField(
            model_name='userprofiletable',
            name='shop_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='balancelog',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfileTable'),
        ),
    ]
