# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_order_dilivery_adress'),
        ('userprofile', '0014_userprofiletable_dilivery_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletable',
            name='shop_delivery_types',
            field=models.ManyToManyField(to='marketplace.DelivertType', verbose_name='Типы доставки'),
        ),
    ]
