# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
