# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0003_auto_20160327_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoryattr',
            unique_together=set([('category', 'subcategory')]),
        ),
    ]
