# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0004_auto_20160329_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryattr',
            name='attrname',
        ),
        migrations.AddField(
            model_name='subcategoryattr',
            name='attrname',
            field=models.ManyToManyField(blank=True, max_length=30, related_name='attrname_set', to='callboard.Attributes', verbose_name='Аттрибуты'),
        ),
    ]
