# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0005_auto_20160329_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'Новый'), ('Old', 'Б/У')], max_length=15, verbose_name='Состояние'),
        ),
    ]
