# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0006_goods_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='condition',
            field=models.CharField(choices=[('New', 'Новый'), ('Old', 'Б/У')], max_length=15, verbose_name='Состояние'),
        ),
    ]
