# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0007_auto_20160329_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
    ]
