# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0010_auto_20160421_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60, verbose_name='Тип')),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard.SubCategory', verbose_name='Подкатегория')),
            ],
        ),
    ]
