# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0011_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60, verbose_name='Тип')),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callboard.SubCategory', verbose_name='Подкатегория')),
            ],
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_set', to='callboard.Type'),
        ),
    ]
