# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0013_goods_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='sub_attr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='callboard.SubCategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
