# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0014_type_sub_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtype',
            name='subcategory',
        ),
    ]
