# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0016_auto_20160909_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtype',
            name='type',
        ),
        migrations.DeleteModel(
            name='SubType',
        ),
    ]
