# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0017_auto_20160909_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='type',
        ),
    ]
