# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0019_goods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='subtype',
            field=models.TextField(blank=True),
        ),
    ]
