# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0020_goods_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='subtype',
        ),
    ]
