# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0023_auto_20160909_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='callboard.Category', verbose_name='Карегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='callboard.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
