# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160923_0942'),
        ('callboard', '0028_auto_20160922_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Cities', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='goods',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.States', verbose_name='Область'),
        ),
    ]
