# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0029_auto_20160923_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_aukc',
            field=models.BooleanField(default=False, verbose_name='На аукционе'),
        ),
    ]
