# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0034_goods_is_aukc1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_aukc1',
        ),
    ]
