# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 09:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0035_remove_goods_is_aukc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
