# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0036_auto_20161010_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Гривна'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='UAH', max_length=3),
        ),
    ]
