# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0046_auto_20161110_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
