# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0048_remove_goods_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('choise', 'Справочник'), ('text', 'Текст')], default='text', max_length=15, verbose_name='Тип поля'),
        ),
        migrations.AddField(
            model_name='attributemap',
            name='attribute_value_manual',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
