# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0049_auto_20161111_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemap',
            name='attribute_value',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='attribute_name', chained_model_field='attribute', null=True, on_delete=django.db.models.deletion.CASCADE, to='callboard.AttributeValue', verbose_name='Значение аттрибута'),
        ),
    ]
