# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0050_auto_20161111_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('choice', 'Справочник'), ('text', 'Текст')], default='text', max_length=15, verbose_name='Тип поля'),
        ),
    ]
