# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0051_auto_20161111_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='filtering',
            field=models.BooleanField(default=False),
        ),
    ]
