# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0053_auto_20161111_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата для сортировки'),
            preserve_default=False,
        ),
    ]
