# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0054_goods_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='key_words',
            field=models.BooleanField(default=False),
        ),
    ]
