# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 10:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0055_attribute_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Аттрибуты'),
        ),
    ]
