# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0059_auto_20161212_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='type',
            new_name='attr_type',
        ),
        migrations.AddField(
            model_name='goods',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_set', to='callboard.Type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='type',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='callboard.Attribute', verbose_name='Доступные аттрибуты'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Тип'),
        ),
    ]
