# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0060_auto_20161212_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='callboard.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
